import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { AddNewEvent } from '../pages/add-new-event/add-new-event';
import { Events } from '../providers/events';
 
@NgModule({
  declarations: [
    MyApp,
    HomePage,
    AddNewEvent
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    AddNewEvent
  ],
  providers: [Events]
})
export class AppModule {}